### ISSUE TITLE
TODO: 微信 API 接口

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/wechat-bot#2]
- [x] 登录
  - [x] `jslogin` 获取 uuid
  - [x] `l/uuid` 获取 QR Code
  - [x] `login` 验证登录
  - [x] `webwxinit` 初始化
  - [x] `webwxstatusnotify` 设置状态通知
- [x] 登出
  - [x] `webwxlogout` 登出
- [x] 新消息
  - [x] `synccheck` 消息状态
  - [x] `webwxsync` 消息详情
- [ ] 消息
  - [x] `webwxsendmsg` 文本消息
  - [ ] `webwxsendmsgimg` 图片消息
  - [x] `webwxsendemoticon` 自定义表情消息（不支持微信商店表情）
  - [ ] `webwxrevokemsg` 撤回消息
- [ ] 联系人
  - [x] `webwxgetcontact` 联系人列表
  - [ ] `webwxbatchgetcontact` 批量获取联系人列表
  - [ ] `webwxverifyuser` 添加好友
- [ ] 图片/文件
  - [ ] `webwxuploadmedia ` 上传图片
  - [x] `webwxgetmsgimg` 获取具体图片
- [ ] 群组
  - [x] `webwxcreatechatroom` 创建群组
  - [ ] `webwxupdatechatroom` 更新群组（修改群组名、添加/删除成员）
